POST http://localhost:3000/users
Content-Type: application/json

{
    "nickname": "test5",
    "password": "safe"
}

###

GET http://localhost:3000/users

###

POST http://localhost:3000/auth
Content-Type: application/json

{
    "nickname": "benko11",
    "password": "maelstrom"
}

###

POST http://localhost:3000/

###

GET http://localhost:3000/auth/secret
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6ImJlbmtvMTEiLCJpYXQiOjE3MjM5MDc5NTYsImV4cCI6MTcyMzkwODAxNn0.To1MfbOZWt3I-AY6-Fg2e2lHlADiFD9nCyXcBjRz4nM